export * from './types';

export * from './Quote';
export * from './Arrow';
export * from './Magic';
export * from './Check';
export * from './Trend';
export * from './Sales';
export * from './Video';
export * from './Heart';
export * from './Ranking';
export * from './Content';
export * from './Lead';
export * from './ChevronDown';
export * from './ChevronLeft';
export * from './ChevronRight';
export * from './LinkedIn';
export * from './X';
export * from './Instagram';
